#!/usr/bin/python3
from sys import argv
import random

def gcd(a, b):
    """Compute the greatest common divisor of two numbers."""
    while b:
        a, b = b, a % b
    return a

def pollard_rho(n):
    """Use Pollard's rho algorithm to find a non-trivial factor of n."""
    if n % 2 == 0:
        return 2
    x = random.randint(1, n-1)
    y = x
    c = random.randint(1, n-1)
    d = 1
    while d == 1:
        x = (x*x + c) % n
        y = (y*y + c) % n
        y = (y*y + c) % n
        d = gcd(abs(x - y), n)
    return d

def factorize(num):
    """Factorize a number into the product of two smaller numbers."""
    factors = []
    while num > 1:
        factor = pollard_rho(num)
        factors.append(factor)
        num //= factor
    return factors

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: {} <file>".format(argv[0]))
        exit(1)
    
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            print("{:d}=".format(num), end="")
            factors = factorize(num)
            if len(factors) == 2:
                print("{}*{}".format(factors[0], factors[1]))
            else:
                print("Cannot factorize further")
