#!/usr/bin/python3
from sys import argv

def is_prime(n):
    """Check if a number is prime."""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize(num):
    """Factorize a number into the product of two smaller numbers."""
     for i in range(2, num // 2 + 1):
        if num % i == 0 and is_prime(i) and is_prime(num // i):
            return (i, num // i)

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: {} <number>".format(argv[0]))
        exit(1)
    
    num = int(argv[1])
    factors = factorize_rsa(num)
    if factors:
        print("{}={}*{}".format(num, factors[0], factors[1]))
    else:
        print("Cannot factorize further")
